apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: secret-pod
    volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/mount-secret"
  volumes:
    - name: secret-volume
      secret:
        secretName: demo-secret
